# Generated by Django 3.2.5 on 2021-11-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalProduct',
            fields=[
                ('product_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('url', models.URLField(blank=True, null=True, verbose_name='source_url')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('item', 'ITEM'), ('event', 'EVENT')], default='event', max_length=10)),
            ],
            options={
                'db_table': 'culturalproduct',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'domain',
            },
        ),
        migrations.CreateModel(
            name='LdaSimilarityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('n_topics', models.IntegerField()),
                ('n_products', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('address_2', models.CharField(max_length=150, null=True)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('zip', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=11)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=150)),
                ('alternative_name', models.CharField(max_length=150, null=True)),
                ('website', models.URLField(max_length=300, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='WebActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='CulturalItem',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dimadb.culturalproduct')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'culturalitem',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='dimadb.culturalproduct')),
                ('status', models.CharField(max_length=16)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='WebActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=50)),
                ('session', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('browser', models.CharField(max_length=80, null=True)),
                ('visitor', models.CharField(max_length=20)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimadb.webactivitytype')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dimadb.location')),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgs', models.ManyToManyField(to='dimadb.Organization', verbose_name='member')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LdaSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.DecimalField(decimal_places=7, max_digits=10)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_product', to='dimadb.culturalproduct')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_product', to='dimadb.culturalproduct')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimadb.ldasimilarityversion')),
            ],
        ),
        migrations.AddField(
            model_name='culturalproduct',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dimadb.domain'),
        ),
        migrations.AddField(
            model_name='culturalproduct',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimadb.organization'),
        ),
        migrations.CreateModel(
            name='ContainProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dimadb.webactivity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimadb.culturalproduct')),
            ],
            options={
                'verbose_name': 'Activity - Product',
            },
        ),
        migrations.CreateModel(
            name='TakePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('weekend', models.BooleanField(verbose_name='is_on_weekend')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dimadb.venue')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dimadb.event')),
            ],
            options={
                'db_table': 'takeplace',
            },
        ),
    ]
