# Generated by Django 3.2.5 on 2021-12-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0003_auto_20211229_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytype',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='count_down',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='recurring_by_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='recurring_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='recurring_freg',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ldasimilarityversion',
            name='n_products',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ldasimilarityversion',
            name='n_topics',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profilecustomer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='webactivities',
            name='activity_duration',
            field=models.IntegerField(null=True),
        ),
    ]
