# Generated by Django 3.2.5 on 2021-12-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0004_auto_20211229_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='isPublic',
            field=models.CharField(choices=[('True', True), ('False', False)], default='True', max_length=10),
        ),
    ]
