# Generated by Django 3.2.5 on 2021-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0006_auto_20211229_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
