# Generated by Django 3.2.5 on 2021-12-29 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0008_alter_webactivities_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
