# Generated by Django 3.2.5 on 2021-12-30 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0011_alter_activitytype_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='price_type',
        ),
    ]
