# Generated by Django 3.2.5 on 2021-12-30 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0012_remove_events_price_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='isPublic',
            new_name='is_public',
        ),
    ]
