# Generated by Django 3.2.5 on 2022-01-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0015_auto_20220101_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importinfo',
            name='table_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
