# Generated by Django 3.2.5 on 2022-01-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0016_alter_importinfo_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='browser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='device_brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='device_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='event_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='operating_system',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='page_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
