# Generated by Django 3.2.5 on 2022-01-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0017_auto_20220103_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='landing_page',
        ),
    ]
