# Generated by Django 3.2.5 on 2022-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0018_remove_session_landing_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
