# Generated by Django 3.2.5 on 2022-01-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0019_auto_20220103_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
