# Generated by Django 3.2.5 on 2022-01-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0020_alter_session_created_at'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='Sessions',
        ),
    ]
