# Generated by Django 3.2.5 on 2022-01-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0021_rename_session_sessions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sessions',
            new_name='SessionData',
        ),
    ]
