# Generated by Django 3.2.5 on 2022-01-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0022_rename_sessions_sessiondata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SessionData',
            new_name='Session',
        ),
    ]
