# Generated by Django 3.2.5 on 2022-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0025_sessionlocation_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldasimilarity',
            name='source',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ldasimilarity',
            name='target',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='ldasimilarity',
            name='version',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
