# Generated by Django 3.2.5 on 2022-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0026_auto_20220112_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldasimilarity',
            name='item_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
