# Generated by Django 3.2.5 on 2022-01-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0027_ldasimilarity_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldasimilarityversion',
            name='item_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
