# Generated by Django 3.2.5 on 2022-01-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0028_ldasimilarityversion_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpreference',
            name='preference_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='productpreference',
            name='preference_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
