# Generated by Django 3.2.5 on 2022-01-16 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0029_auto_20220116_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webactivitytype',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='webactivitytype',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
