# Generated by Django 3.2.5 on 2022-01-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0030_auto_20220116_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('location_id', models.CharField(blank=True, max_length=50, null=True)),
                ('import_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='interaction',
            name='browser',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='device_brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='device_category',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='event_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='operating_system',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='page_location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='page_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='interaction',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
