# Generated by Django 3.2.5 on 2022-01-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dimadb', '0031_auto_20220119_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='is_entrance',
            field=models.CharField(blank=True, choices=[('True', True), ('False', False)], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='is_exit',
            field=models.CharField(blank=True, choices=[('True', True), ('False', False)], max_length=10, null=True),
        ),
    ]
